# You can find color codes here: https://minecraft.tools/en/color-code.php
# Formatting comes after the color! &d&l will work, but not &l&d.
# Placeholders: %online% (Players online)
# %max% (Server max slots)
# %newline% adds a newline to your motd.
# %tps% shows the tps (Paper only)
motd:
  activated: true
  text:
    - "Hello! %newline%World!"
    - "Use &4color codes!"
    - "&ka &rFormatting &rworks &rtoo! &ka"
    - "&1Players: %online%"
    - "&2Max: %max%"

overridemax:
  activated: false
  value: 10

# Extended config only works on paper https://papermc.io/
# On paper you also get the %tps% placeholder
extended:
  # A protocol message is shown if the version of the client doesn't match the version of the server.
  # %aftericon% adds a bunch of spaces so the text is after the icon. (Only for protocol)
  protocol:
    activated: false
    text: "&1My custom protocol message!"
  overrideonline:
    activated: false
    value: 0
  # Instead of showing the playerstats the client will just display "???"
  hideplayers: false
  # This is shown when you hover over the playercount
  playercounter:
    activated: true
    text:
      - "&3Hello world!"
      - "&eNewline!"
      - "&6    spaces!"
      - "&d&lCombined"
      - "&1Players: %online%"
      - "&2Max: %max%"