playercounter:
  bukkitplayercounter: false
  activated: true
  text:
    - "&3Hello world!"
    - "&eNewline!"
    - "&6    spaces!"
    - "&d&lCombined"
    - "&1Players: %online%"
    - "&2Max: %max%"

overrideonline:
  activated: false
  value: 0

overridemax:
  activated: false
  value: 10

protocol:
  activated: true
  text: "&1My custom protocol message!"

overrideprotocolnumber:
  activated: false
  value: 1

icons: false

hooks:
  luckpermsplayercounter: false

motd:
  activated: true
  text:
    - "Hello! %newline%World!"
    - "Use &4color codes!"
    - "&ka &rFormatting &rworks &rtoo! &ka"
    - "&1Players: %online%"
    - "&2Max: %max%"